'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowRight } from 'lucide-react';
import { sectionVariants } from '@/lib/animations';
import { ClayCard } from '@/components/ui/ClayCard';
import { useTextScramble } from '@/hooks/useTextScramble';
import { useTranslations } from '@/components/i18n/LocaleProvider';

export function InvisibilityTax() {
  const { t: tHome } = useTranslations('home');
  const eyebrow = tHome('invisibilityTax.eyebrow', '[ THE INVISIBLE TAX ]');
  const invisibleTaxScramble = useTextScramble(eyebrow, 900, true, 3000);

  const stats = [
    {
      value: tHome('invisibilityTax.stat1Value', '75%'),
      caption: tHome('invisibilityTax.stat1Caption', "of users judge a company's credibility based on their website design."),
      source: tHome('invisibilityTax.stat1Source', 'Stanford Web Credibility Research'),
    },
    {
      value: tHome('invisibilityTax.stat2Value', '88%'),
      caption: tHome('invisibilityTax.stat2Caption', 'of online consumers are less likely to return to a site after a bad experience.'),
      source: tHome('invisibilityTax.stat2Source', 'Adobe UX Survey'),
    },
    {
      value: tHome('invisibilityTax.stat3Value', '1 second'),
      caption: tHome('invisibilityTax.stat3Caption', 'delay in page load time reduces conversions by 7% per second of delay.'),
      source: tHome('invisibilityTax.stat3Source', 'Akamai / Google'),
    },
    {
      value: tHome('invisibilityTax.stat4Value', '3.5×'),
      caption: tHome(
        'invisibilityTax.stat4Caption',
        'more qualified leads generated by businesses with SEO-optimized, high-performance websites vs. those without.',
      ),
      source: tHome('invisibilityTax.stat4Source', 'HubSpot State of Marketing'),
    },
  ];

  return (
    <section
      className="border-t border-[var(--border)] bg-[var(--bg-base)] py-[var(--section-py)] md:py-[var(--section-py-lg)]"
      aria-labelledby="invisibility-tax-heading"
    >
      <motion.div
        className="tw-section"
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: '-10% 0px' }}
        variants={sectionVariants}
      >
        <p className="tw-prose-flow mb-4 max-w-full font-display text-[clamp(0.756rem,2vw,0.98rem)] font-bold uppercase leading-snug tracking-[0.2em] text-[var(--brand)] sm:text-[clamp(0.81rem,1.6vw,1.02rem)]">
          {invisibleTaxScramble}
        </p>
        <h2
          id="invisibility-tax-heading"
          className="tw-heading-section tw-prose-flow max-w-none font-display font-bold tracking-tight text-[var(--fg-primary)]"
        >
          {tHome('invisibilityTax.heading', 'Profitable businesses are bleeding revenue online, every day.')}
        </h2>

        <div className="mt-12 space-y-10">
          <div className="min-w-0 max-w-4xl font-sans text-base font-normal leading-[1.6] text-[var(--fg-secondary)]">
            <p className="mb-6 text-[var(--fg-primary)]">
              {tHome('invisibilityTax.scenarioIntro', 'Here is a scenario most founders recognize but rarely quantify.')}
            </p>
            <p className="mb-6">
              {tHome(
                'invisibilityTax.scenarioP1',
                "A serious buyer searches for your service. They find a competitor first, not because the competitor is better, but because their website loads in 1.2 seconds instead of 6.4. Their headline answers the buyer's question. Their CTA is visible above the fold. Your site is not.",
              )}
            </p>
            <p className="mb-6">
              {tHome('invisibilityTax.scenarioP2', 'You never knew the lead existed. The competitor closed the deal.')}
            </p>
            <p>{tHome('invisibilityTax.scenarioP3', 'This is not a marketing problem. It is an infrastructure problem.')}</p>
          </div>

          <div className="grid min-w-0 grid-cols-1 items-stretch gap-6 md:grid-cols-2">
            {stats.map((card) => (
              <ClayCard
                as="article"
                key={card.value}
                className="min-w-0 overflow-hidden p-6 pl-5"
                style={{ borderLeftWidth: 3, borderLeftColor: 'var(--brand)' }}
              >
                <p className="max-w-full break-words font-display text-[clamp(1.65rem,calc(9vw+0.35rem),3.25rem)] font-extrabold leading-[1.05] tracking-tight text-[var(--brand)] sm:text-[clamp(2rem,calc(6vw+0.75rem),3.5rem)]">
                  {card.value}
                </p>
                <p className="mt-4 font-sans text-sm font-light leading-relaxed text-[var(--fg-secondary)]">{card.caption}</p>
                <p className="mt-4 font-mono text-[10px] uppercase tracking-wider text-[var(--fg-tertiary)]">{card.source}</p>
              </ClayCard>
            ))}
          </div>
        </div>

        <div className="mt-16 border-t border-[var(--border)] pt-12 text-center">
          <p className="mx-auto max-w-2xl font-sans text-base italic leading-[1.8] text-[var(--fg-secondary)]">
            {tHome(
              'invisibilityTax.closingQuote',
              'Not having a great website is not a cost you can see on a spreadsheet. It is the revenue that never appeared.',
            )}
          </p>
          <Link
            href="#what-we-do"
            className="mt-8 inline-flex items-center gap-2 font-sans text-sm font-medium text-[var(--brand)] transition-colors hover:text-[var(--brand-hover)]"
          >
            {tHome('invisibilityTax.cta', 'Build the infrastructure that captures it')}
            <ArrowRight className="h-4 w-4" aria-hidden />
          </Link>
        </div>
      </motion.div>
    </section>
  );
}
