export type CitySeoData = {
  slug: string;
  name: string;
  state: string;
  lat: number;
  lng: number;
  marketInsight: string;
  localPainPoints: string[];
  localIndustries: string[];
  localKeywords: string[];
  relatedBlogSlugs: string[];
};

export const CITY_SERVICE_SLUGS = [
  'web-development',
  'digital-marketing',
  'custom-software',
  'ai-agents-automations',
] as const;

export const cities: CitySeoData[] = [
  {
    slug: 'lucknow',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    lat: 26.8467,
    lng: 80.9462,
    marketInsight: 'Rapid local service-business digitization and stronger search-driven lead demand across healthcare, education, and real estate.',
    localPainPoints: ['Outdated websites with weak conversion funnels', 'Low map-pack visibility despite ad spend', 'Poor lead attribution between WhatsApp and web forms'],
    localIndustries: ['Healthcare', 'Education', 'Real Estate', 'Professional Services'],
    localKeywords: ['best web agency Lucknow', 'SEO agency Lucknow', 'website developer Lucknow'],
    relatedBlogSlugs: [
      'local-seo-audit-lucknow-checklist-that-finds-revenue-gaps',
      'ui-ux-design-agency-lucknow-conversion-playbook',
      'website-speed-optimization-lucknow-why-slow-sites-lose-leads',
      'meta-ads-lead-generation-lucknow-quality-funnel',
      'google-business-profile-optimization-kanpur-rank-and-convert',
      'lead-nurture-whatsapp-automation-uttar-pradesh',
    ],
  },
  {
    slug: 'delhi',
    name: 'Delhi',
    state: 'Delhi NCR',
    lat: 28.6139,
    lng: 77.209,
    marketInsight: 'Hyper-competitive B2B and D2C search market where technical SEO and conversion-led UX create the biggest moat.',
    localPainPoints: ['Paid traffic dependence with weak organic authority', 'Fragmented brand messaging across web and social', 'Slow websites causing CPL inflation'],
    localIndustries: ['SaaS', 'Professional Services', 'Ecommerce', 'Healthcare'],
    localKeywords: ['best web agency Delhi', 'SEO company Delhi NCR', 'website development company Delhi'],
    relatedBlogSlugs: [
      'technical-seo-checklist-india-2026-priority-fixes',
      'seo-and-ppc-synergy-for-local-lead-generation-system',
      'conversion-rate-optimization-checklist-website-lead-gen',
      'agency-selection-checklist-for-founders-no-fluff',
      'marketing-budget-planning-quarter-wise-founder-guide',
      'website-conversion-tracking-implementation-guide-ga4-gtm',
    ],
  },
  {
    slug: 'noida',
    name: 'Noida',
    state: 'Uttar Pradesh',
    lat: 28.5355,
    lng: 77.391,
    marketInsight: 'High-growth startup and IT corridor where speed-to-market and full-funnel analytics decide winners.',
    localPainPoints: ['Template sites unable to rank for high-intent terms', 'Disconnected CRM and campaign data', 'No local landing page strategy for NCR intent'],
    localIndustries: ['IT Services', 'SaaS', 'Education', 'Real Estate'],
    localKeywords: ['web design agency Noida', 'website developer Noida', 'digital growth agency Noida'],
    relatedBlogSlugs: [
      'local-landing-pages-for-multi-city-seo-framework',
      'internal-linking-strategy-local-seo-clusters-practical-playbook',
      'funnel-analytics-for-service-businesses-india-operator-guide',
      'growth-ops-for-small-service-businesses-india-playbook',
      'custom-website-vs-template-for-lead-generation-india',
      'page-speed-fixes-that-improve-lead-conversion-checklist',
    ],
  },
  {
    slug: 'gurugram',
    name: 'Gurugram',
    state: 'Haryana',
    lat: 28.4595,
    lng: 77.0266,
    marketInsight: 'Enterprise and startup demand is strong, but intent capture needs sharper technical architecture and narrative authority.',
    localPainPoints: ['Weak service differentiation in SERPs', 'Thin content on high-value service pages', 'Low trust signals on landing pages'],
    localIndustries: ['Enterprise Services', 'Fintech', 'SaaS', 'Consulting'],
    localKeywords: ['web development company Gurugram', 'SEO agency Gurgaon', 'UI UX agency Gurugram'],
    relatedBlogSlugs: [
      'website-trust-signals-that-boost-conversions-india',
      'authority-building-through-technical-content-hubs',
      'founder-marketing-systems-north-india-scale-without-chaos',
      'pricing-strategy-for-digital-services-founder-framework',
      'agency-scorecard-for-monthly-performance-review',
      'weekly-growth-review-meeting-format-for-founders',
    ],
  },
  {
    slug: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    lat: 19.076,
    lng: 72.8777,
    marketInsight: 'Performance-led market with high CAC pressure where conversion engineering and SEO architecture provide compounding gains.',
    localPainPoints: ['Ad-heavy growth with weak retention loops', 'Under-optimized mobile UX for transactional audiences', 'Inconsistent local citation footprint'],
    localIndustries: ['D2C', 'Finance', 'Healthcare', 'Media'],
    localKeywords: ['best web agency Mumbai', 'SEO agency Mumbai', 'performance marketing agency Mumbai'],
    relatedBlogSlugs: [
      'mobile-first-website-optimization-for-india-conversion-guide',
      'retargeting-strategy-for-local-businesses-india-growth-loop',
      'reducing-cost-per-qualified-lead-without-killing-volume',
      'google-ads-vs-meta-ads-local-smb-india-decision-guide',
      'budget-allocation-google-and-meta-for-smb-growth',
      'campaign-structure-for-multi-location-brands-india',
    ],
  },
  {
    slug: 'bangalore',
    name: 'Bangalore',
    state: 'Karnataka',
    lat: 12.9716,
    lng: 77.5946,
    marketInsight: 'Product-led and SaaS-heavy ecosystem where technical content authority drives both inbound leads and hiring brand.',
    localPainPoints: ['Missed bottom-funnel comparison traffic', 'Slow feature pages with weak technical depth', 'Poor schema implementation on service pages'],
    localIndustries: ['SaaS', 'Product Startups', 'DevTools', 'AI'],
    localKeywords: ['website developer Bangalore', 'technical SEO agency Bangalore', 'AI automation agency Bangalore'],
    relatedBlogSlugs: [
      'nextjs-seo-architecture-for-service-websites-2026',
      'seo-architecture-technical-foundations-organic-growth-2026',
      'faq-schema-for-service-pages-india-seo-implementation-guide',
      'design-systems-for-faster-website-iteration-practical-playbook',
      'building-scalable-web-apps-hyper-growth-ecommerce',
      'headless-commerce-2026-flexibility-scale',
    ],
  },
  {
    slug: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    lat: 17.385,
    lng: 78.4867,
    marketInsight: 'Tech + healthcare demand is scaling fast; integrated SEO + paid + automation systems outperform isolated channels.',
    localPainPoints: ['Siloed teams with no unified growth dashboard', 'Weak technical SEO in multilingual environments', 'No clear funnel handoff to sales'],
    localIndustries: ['Tech Services', 'Healthcare', 'Education', 'Manufacturing'],
    localKeywords: ['SEO agency Hyderabad', 'web development company Hyderabad', 'digital agency Hyderabad'],
    relatedBlogSlugs: [
      'building-predictable-lead-pipeline-smb-operator-guide',
      'sales-marketing-handoff-system-smb-implementation',
      'kpi-dashboard-for-founders-marketing-spend-operator-template',
      'performance-dashboard-for-local-campaigns-what-to-track',
      'funnel-analytics-for-service-businesses-india-operator-guide',
      'call-tracking-setup-for-paid-campaigns-smb-guide',
    ],
  },
  {
    slug: 'pune',
    name: 'Pune',
    state: 'Maharashtra',
    lat: 18.5204,
    lng: 73.8567,
    marketInsight: 'Strong SMB and startup base where authority content plus technical delivery helps close higher-ticket contracts.',
    localPainPoints: ['Low branded search growth', 'Weak content depth on services', 'Limited social proof integration'],
    localIndustries: ['SaaS', 'Education', 'Professional Services', 'Automotive'],
    localKeywords: ['web agency Pune', 'SEO services Pune', 'website design Pune'],
    relatedBlogSlugs: [
      'build-marketing-moat-for-services-business-in-india',
      'high-intent-lead-magnets-for-local-services-framework',
      'landing-page-copy-framework-b2b-services-conversion',
      'website-redesign-for-lead-generation-up-operational-guide',
      'founder-guide-to-agency-onboarding-no-chaos-playbook',
      'founder-communication-templates-for-sales-teams',
    ],
  },
  {
    slug: 'chennai',
    name: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0827,
    lng: 80.2707,
    marketInsight: 'B2B and manufacturing-oriented city where clarity in technical content and service credibility drives discovery.',
    localPainPoints: ['Legacy websites without modern schema', 'Low conversion from informational traffic', 'Inconsistent SERP snippets and CTR'],
    localIndustries: ['Manufacturing', 'B2B Services', 'Healthcare', 'Education'],
    localKeywords: ['web development company Chennai', 'SEO agency Chennai', 'software company Chennai'],
    relatedBlogSlugs: [
      'why-website-not-ranking-india-fix-founder-playbook',
      'seo-audit-mistakes-agencies-make-and-how-to-avoid',
      'audit-website-forms-for-conversion-loss-practical-guide',
      'technical-website-audit-for-lead-leakage-checklist',
      'map-pack-vs-organic-ranking-india-what-drives-revenue',
      'zero-click-search-local-seo-strategy-india-2026',
    ],
  },
  {
    slug: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    lat: 23.0225,
    lng: 72.5714,
    marketInsight: 'Growing digital adoption in traditional sectors where localized landing pages unlock high-intent organic traffic.',
    localPainPoints: ['Generic websites not tailored for local search intent', 'Weak local citation consistency', 'No performance-focused redesign roadmap'],
    localIndustries: ['Manufacturing', 'Textiles', 'Healthcare', 'Professional Services'],
    localKeywords: ['web design agency Ahmedabad', 'SEO agency Ahmedabad', 'website developer Ahmedabad'],
    relatedBlogSlugs: [
      'on-page-seo-for-city-specific-pages-india-framework',
      'local-citations-strategy-uttar-pradesh-rankings',
      'local-seo-for-clinics-in-uttar-pradesh-growth-blueprint',
      'map-pack-vs-organic-ranking-india-what-drives-revenue',
      'website-speed-optimization-lucknow-why-slow-sites-lose-leads',
      'conversion-focused-landing-page-development-up-playbook',
    ],
  },
  {
    slug: 'jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    lat: 26.9124,
    lng: 75.7873,
    marketInsight: 'Rising startup and tourism commerce ecosystem where semantic local pages and stronger trust signals boost leads.',
    localPainPoints: ['Low-quality traffic from broad keywords', 'Thin service pages without buyer-stage mapping', 'Missing structured trust proof'],
    localIndustries: ['Tourism', 'Healthcare', 'Education', 'D2C'],
    localKeywords: ['web agency Jaipur', 'SEO services Jaipur', 'website development Jaipur'],
    relatedBlogSlugs: [
      'search-intent-mapping-for-service-businesses-india-guide',
      'website-trust-signals-that-boost-conversions-india',
      'conversion-focused-landing-page-development-up-playbook',
      'high-intent-lead-magnets-for-local-services-framework',
      'seo-and-ppc-synergy-for-local-lead-generation-system',
      'performance-creatives-for-local-audiences-testing-playbook',
    ],
  },
  {
    slug: 'chandigarh',
    name: 'Chandigarh',
    state: 'Chandigarh',
    lat: 30.7333,
    lng: 76.7794,
    marketInsight: 'Strong regional business hub where city-specific positioning and fast websites deliver outsized ranking gains.',
    localPainPoints: ['Poor mobile conversion rates', 'Limited content depth for local services', 'No clear authority narrative in search'],
    localIndustries: ['Healthcare', 'Legal', 'Education', 'Professional Services'],
    localKeywords: ['web design agency Chandigarh', 'SEO company Chandigarh', 'website developer Chandigarh'],
    relatedBlogSlugs: [
      'mobile-first-website-optimization-for-india-conversion-guide',
      'website-redesign-for-lead-generation-up-operational-guide',
      'authority-building-through-technical-content-hubs',
      'build-marketing-moat-for-services-business-in-india',
      'growth-ops-for-small-service-businesses-india-playbook',
      'weekly-growth-review-meeting-format-for-founders',
    ],
  },
  {
    slug: 'kolkata',
    name: 'Kolkata',
    state: 'West Bengal',
    lat: 22.5726,
    lng: 88.3639,
    marketInsight: 'Mature SMB market where process-driven SEO, analytics discipline, and conversion UX are underutilized opportunities.',
    localPainPoints: ['Poor technical hygiene and crawl architecture', 'No consistent local content cadence', 'Weak conversion instrumentation'],
    localIndustries: ['Healthcare', 'Education', 'Finance', 'Retail'],
    localKeywords: ['best web agency Kolkata', 'SEO services Kolkata', 'web development Kolkata'],
    relatedBlogSlugs: [
      'technical-seo-checklist-india-2026-priority-fixes',
      'website-conversion-tracking-implementation-guide-ga4-gtm',
      'local-landing-pages-for-multi-city-seo-framework',
      'internal-linking-strategy-local-seo-clusters-practical-playbook',
      'agency-scorecard-for-monthly-performance-review',
      'performance-dashboard-for-local-campaigns-what-to-track',
    ],
  },
  {
    slug: 'kanpur',
    name: 'Kanpur',
    state: 'Uttar Pradesh',
    lat: 26.4499,
    lng: 80.3319,
    marketInsight: 'Fast-growing digital demand where local map+organic strategy can dominate competitors with weaker web stacks.',
    localPainPoints: ['Low GBP optimization maturity', 'Outdated ecommerce systems', 'No structured lead nurturing flow'],
    localIndustries: ['Ecommerce', 'Healthcare', 'Education', 'Local Services'],
    localKeywords: ['web development company Kanpur', 'SEO agency Kanpur', 'website developer Kanpur'],
    relatedBlogSlugs: [
      'ecommerce-website-development-kanpur-growth-playbook',
      'google-business-profile-optimization-kanpur-rank-and-convert',
      'lead-nurture-whatsapp-automation-uttar-pradesh',
      'local-seo-for-clinics-in-uttar-pradesh-growth-blueprint',
      'map-pack-vs-organic-ranking-india-what-drives-revenue',
      'retargeting-strategy-for-local-businesses-india-growth-loop',
    ],
  },
  {
    slug: 'varanasi',
    name: 'Varanasi',
    state: 'Uttar Pradesh',
    lat: 25.3176,
    lng: 82.9739,
    marketInsight: 'Local commerce digitization is accelerating, and first-movers with city-focused pages can capture substantial high-intent demand.',
    localPainPoints: ['Low local keyword coverage', 'Weak trust signals for first-time buyers', 'No systematic content-to-lead funnel'],
    localIndustries: ['Healthcare', 'Education', 'Tourism', 'Professional Services'],
    localKeywords: ['web agency Varanasi', 'SEO agency Varanasi', 'website design Varanasi'],
    relatedBlogSlugs: [
      'local-landing-pages-for-multi-city-seo-framework',
      'local-citations-strategy-uttar-pradesh-rankings',
      'high-intent-lead-magnets-for-local-services-framework',
      'landing-page-copy-framework-b2b-services-conversion',
      'website-trust-signals-that-boost-conversions-india',
      'why-gmb-views-not-turning-into-leads-fix-guide',
    ],
  },
];

export const citiesBySlug = new Map(cities.map((city) => [city.slug, city]));
